//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.ImportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImportService.IImportService")]
    public interface IImportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTemplateDataByObject", ReplyAction="http://tempuri.org/IImportService/GetTemplateDataByObjectResponse")]
        System.Data.DataSet GetTemplateDataByObject(string Object, long UserID, long CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/InsertImportLocation", ReplyAction="http://tempuri.org/IImportService/InsertImportLocationResponse")]
        long InsertImportLocation(string Object, long UserID, long CompanyID, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DeleteFromtempTable", ReplyAction="http://tempuri.org/IImportService/DeleteFromtempTableResponse")]
        void DeleteFromtempTable(string Object, long UserID, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/NewValidateImportData", ReplyAction="http://tempuri.org/IImportService/NewValidateImportDataResponse")]
        void NewValidateImportData(string Object, long UserID, long CompanyID, System.Data.DataSet ImportData, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/getTempTableValue", ReplyAction="http://tempuri.org/IImportService/getTempTableValueResponse")]
        System.Data.DataSet getTempTableValue(string Object, long UserID, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/ValidateImportDataMorethan100", ReplyAction="http://tempuri.org/IImportService/ValidateImportDataMorethan100Response")]
        void ValidateImportDataMorethan100(string Object, long UserID, long CompanyID, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTemptablerecordCount", ReplyAction="http://tempuri.org/IImportService/GetTemptablerecordCountResponse")]
        long GetTemptablerecordCount(string Object, long UserID, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/AddRecordToschedular", ReplyAction="http://tempuri.org/IImportService/AddRecordToschedularResponse")]
        void AddRecordToschedular(string TaskCode, string Object, long CompanyID, long CustomerID, long WarehouseID, long TotalNoOfRecords, string Status, long CreatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetSchedulebyObject", ReplyAction="http://tempuri.org/IImportService/GetSchedulebyObjectResponse")]
        System.Data.DataSet GetSchedulebyObject(string Object, long CompanyID, long CustomerID, long CreatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetScheduleCount", ReplyAction="http://tempuri.org/IImportService/GetScheduleCountResponse")]
        long GetScheduleCount(string Object, long CompanyID, long CustomerID, long CreatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetUserCustomer", ReplyAction="http://tempuri.org/IImportService/GetUserCustomerResponse")]
        System.Data.DataSet GetUserCustomer(long uid, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDistinctPLCodes", ReplyAction="http://tempuri.org/IImportService/GetDistinctPLCodesResponse")]
        System.Data.DataSet GetDistinctPLCodes(long CreatedBy, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/NewInsertVTImportdata", ReplyAction="http://tempuri.org/IImportService/NewInsertVTImportdataResponse")]
        long NewInsertVTImportdata(string Object, long Deptid, long LocId, long ProjectID, long SiteID, long CreatedBy, long CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDistictSKUSchemaforSerial", ReplyAction="http://tempuri.org/IImportService/GetDistictSKUSchemaforSerialResponse")]
        System.Data.DataSet GetDistictSKUSchemaforSerial(long CreatedBy, long CustomerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImportServiceChannel : PowerOnRentwebapp.ImportService.IImportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportServiceClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.ImportService.IImportService>, PowerOnRentwebapp.ImportService.IImportService {
        
        public ImportServiceClient() {
        }
        
        public ImportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetTemplateDataByObject(string Object, long UserID, long CustomerId) {
            return base.Channel.GetTemplateDataByObject(Object, UserID, CustomerId);
        }
        
        public long InsertImportLocation(string Object, long UserID, long CompanyID, long CustomerID) {
            return base.Channel.InsertImportLocation(Object, UserID, CompanyID, CustomerID);
        }
        
        public void DeleteFromtempTable(string Object, long UserID, long CustomerID) {
            base.Channel.DeleteFromtempTable(Object, UserID, CustomerID);
        }
        
        public void NewValidateImportData(string Object, long UserID, long CompanyID, System.Data.DataSet ImportData, long CustomerID) {
            base.Channel.NewValidateImportData(Object, UserID, CompanyID, ImportData, CustomerID);
        }
        
        public System.Data.DataSet getTempTableValue(string Object, long UserID, long CustomerID) {
            return base.Channel.getTempTableValue(Object, UserID, CustomerID);
        }
        
        public void ValidateImportDataMorethan100(string Object, long UserID, long CompanyID, long CustomerID) {
            base.Channel.ValidateImportDataMorethan100(Object, UserID, CompanyID, CustomerID);
        }
        
        public long GetTemptablerecordCount(string Object, long UserID, long CustomerID) {
            return base.Channel.GetTemptablerecordCount(Object, UserID, CustomerID);
        }
        
        public void AddRecordToschedular(string TaskCode, string Object, long CompanyID, long CustomerID, long WarehouseID, long TotalNoOfRecords, string Status, long CreatedBy) {
            base.Channel.AddRecordToschedular(TaskCode, Object, CompanyID, CustomerID, WarehouseID, TotalNoOfRecords, Status, CreatedBy);
        }
        
        public System.Data.DataSet GetSchedulebyObject(string Object, long CompanyID, long CustomerID, long CreatedBy) {
            return base.Channel.GetSchedulebyObject(Object, CompanyID, CustomerID, CreatedBy);
        }
        
        public long GetScheduleCount(string Object, long CompanyID, long CustomerID, long CreatedBy) {
            return base.Channel.GetScheduleCount(Object, CompanyID, CustomerID, CreatedBy);
        }
        
        public System.Data.DataSet GetUserCustomer(long uid, string[] conn) {
            return base.Channel.GetUserCustomer(uid, conn);
        }
        
        public System.Data.DataSet GetDistinctPLCodes(long CreatedBy, long CustomerID) {
            return base.Channel.GetDistinctPLCodes(CreatedBy, CustomerID);
        }
        
        public long NewInsertVTImportdata(string Object, long Deptid, long LocId, long ProjectID, long SiteID, long CreatedBy, long CustomerID) {
            return base.Channel.NewInsertVTImportdata(Object, Deptid, LocId, ProjectID, SiteID, CreatedBy, CustomerID);
        }
        
        public System.Data.DataSet GetDistictSKUSchemaforSerial(long CreatedBy, long CustomerID) {
            return base.Channel.GetDistictSKUSchemaforSerial(CreatedBy, CustomerID);
        }
    }
}
