//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.RTSerialStock {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSerial", Namespace="http://schemas.datacontract.org/2004/07/RealTimeSerialStockService")]
    [System.SerializableAttribute()]
    public partial class GetSerial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SERIALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QTY {
            get {
                return this.QTYField;
            }
            set {
                if ((this.QTYField.Equals(value) != true)) {
                    this.QTYField = value;
                    this.RaisePropertyChanged("QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERIAL {
            get {
                return this.SERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.SERIALField, value) != true)) {
                    this.SERIALField = value;
                    this.RaisePropertyChanged("SERIAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RTSerialStock.ISerialRTimeStockService")]
    public interface ISerialRTimeStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerialRTimeStockService/CheckAvailableQty", ReplyAction="http://tempuri.org/ISerialRTimeStockService/CheckAvailableQtyResponse")]
        System.Collections.Generic.List<PowerOnRentwebapp.RTSerialStock.GetSerial> CheckAvailableQty(string SKUCode, string DepartmentCode, string Database, string connection, string schema);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISerialRTimeStockServiceChannel : PowerOnRentwebapp.RTSerialStock.ISerialRTimeStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerialRTimeStockServiceClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.RTSerialStock.ISerialRTimeStockService>, PowerOnRentwebapp.RTSerialStock.ISerialRTimeStockService {
        
        public SerialRTimeStockServiceClient() {
        }
        
        public SerialRTimeStockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerialRTimeStockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialRTimeStockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialRTimeStockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<PowerOnRentwebapp.RTSerialStock.GetSerial> CheckAvailableQty(string SKUCode, string DepartmentCode, string Database, string connection, string schema) {
            return base.Channel.CheckAvailableQty(SKUCode, DepartmentCode, Database, connection, schema);
        }
    }
}
