//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.AvailableQtyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AvailableQtyService.ICheckStockAvailable")]
    public interface ICheckStockAvailable {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckStockAvailable/CheckAvailableQty", ReplyAction="http://tempuri.org/ICheckStockAvailable/CheckAvailableQtyResponse")]
        decimal CheckAvailableQty(string SKUCode, string DepartmentCode, string Database, string connection, string schema);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckStockAvailableChannel : PowerOnRentwebapp.AvailableQtyService.ICheckStockAvailable, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckStockAvailableClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.AvailableQtyService.ICheckStockAvailable>, PowerOnRentwebapp.AvailableQtyService.ICheckStockAvailable {
        
        public CheckStockAvailableClient() {
        }
        
        public CheckStockAvailableClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckStockAvailableClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckStockAvailableClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckStockAvailableClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal CheckAvailableQty(string SKUCode, string DepartmentCode, string Database, string connection, string schema) {
            return base.Channel.CheckAvailableQty(SKUCode, DepartmentCode, Database, connection, schema);
        }
    }
}
